"""Turn non-planar layers into Marlin-style G-code.

Every extrusion move carries X, Y and Z. Extrusion is relative (M83) and is
computed per segment from the real 3D segment length and the local layer
thickness, so the parts of a layer that sit higher above the one below get
more plastic.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

from .geometry import Layer, WallParams, generate_layers, wall_stats


@dataclass
class PrinterParams:
    bed_center_x: float = 110.0
    bed_center_y: float = 110.0
    filament_diameter: float = 1.75
    flow: float = 1.0
    nozzle_temp: int = 210
    bed_temp: int = 60
    print_speed: float = 25.0  # mm/s
    first_layer_speed: float = 15.0  # mm/s
    travel_speed: float = 120.0  # mm/s
    max_z_speed: float = 10.0  # mm/s, only used for the warning / time estimate
    retract_length: float = 0.8  # mm
    retract_speed: float = 35.0  # mm/s
    fan_percent: int = 100
    fan_from_layer: int = 2


START_GCODE = """G90 ; absolute XYZ
M83 ; relative extrusion
M140 S{bed_temp}
M104 S{nozzle_temp}
G28 ; home
M190 S{bed_temp}
M109 S{nozzle_temp}
G92 E0
; purge line
G1 Z2 F600
G1 X{purge_x:.2f} Y{purge_y0:.2f} F{travel_f:.0f}
G1 Z0.3 F600
G1 X{purge_x:.2f} Y{purge_y1:.2f} E12 F900
G1 Z2 F600
"""

END_GCODE = """G1 E-{retract:.2f} F{retract_f:.0f}
G91
G1 Z10 F600 ; lift
G90
M104 S0
M140 S0
M107
G1 X0 Y{park_y:.2f} F{travel_f:.0f}
M84
"""


def _extrusion_per_mm(printer: PrinterParams, width: float, thickness: np.ndarray) -> np.ndarray:
    """Filament length per mm of path, using a rectangle-with-round-ends bead."""
    thickness = np.clip(thickness, 0.0, None)
    area = (width - thickness) * thickness + math.pi * (thickness / 2.0) ** 2
    area = np.where(width > thickness, area, width * thickness)
    filament_area = math.pi * (printer.filament_diameter / 2.0) ** 2
    return printer.flow * area / filament_area


def build_gcode(wall: WallParams, printer: PrinterParams,
                layers: list[Layer] | None = None) -> tuple[str, dict]:
    """Return (gcode text, summary dict)."""
    if layers is None:
        layers = generate_layers(wall)
    stats = wall_stats(wall, layers)
    cx, cy = printer.bed_center_x, printer.bed_center_y

    out: list[str] = []
    out.append("; Non-planar wave wall generated by nonplanar_slicer")
    for key, value in vars(wall).items():
        out.append(f"; wall.{key} = {value}")
    for key, value in vars(printer).items():
        out.append(f"; printer.{key} = {value}")
    out.append(f"; layers = {stats.layers}")
    out.append(f"; local layer thickness = {stats.min_thickness:.3f} .. {stats.max_thickness:.3f} mm")
    out.append(f"; max surface slope = {stats.max_slope_deg:.1f} deg")

    out.append(START_GCODE.format(
        bed_temp=printer.bed_temp,
        nozzle_temp=printer.nozzle_temp,
        purge_x=5.0,
        purge_y0=20.0,
        purge_y1=120.0,
        travel_f=printer.travel_speed * 60,
    ))

    total_e = 0.0
    total_time = 0.0
    max_z_rate = 0.0
    pos = None  # current nozzle position
    retracted = False
    travel_f = printer.travel_speed * 60

    for layer in layers:
        out.append(f";LAYER:{layer.index}")
        if layer.index == printer.fan_from_layer:
            out.append(f"M106 S{round(255 * printer.fan_percent / 100)}")
        speed = printer.first_layer_speed if layer.index == 0 else printer.print_speed
        feed = speed * 60

        for path in layer.paths:
            pts = path.points.copy()
            pts[:, 0] += cx
            pts[:, 1] += cy
            start = pts[0]

            dist = math.inf if pos is None else float(np.linalg.norm(start - pos))
            if dist > 1e-6:
                if dist > 2.0:
                    if not retracted:
                        out.append(f"G1 E-{printer.retract_length:.3f} F{printer.retract_speed * 60:.0f}")
                        retracted = True
                    # Hop above the target before moving sideways so we never drag
                    # through the wavy wall, then drop onto the start point.
                    hop_z = max(start[2], pos[2] if pos is not None else 0.0) + 1.0
                    out.append(f"G0 Z{hop_z:.3f} F{printer.max_z_speed * 60:.0f}")
                    out.append(f"G0 X{start[0]:.3f} Y{start[1]:.3f} F{travel_f:.0f}")
                    out.append(f"G0 Z{start[2]:.3f} F{printer.max_z_speed * 60:.0f}")
                    if pos is not None:
                        total_time += dist / printer.travel_speed
                    total_time += 2.0 / printer.max_z_speed
                else:
                    out.append(f"G0 X{start[0]:.3f} Y{start[1]:.3f} Z{start[2]:.3f} F{travel_f:.0f}")
                    total_time += dist / printer.travel_speed
            if retracted:
                out.append(f"G1 E{printer.retract_length:.3f} F{printer.retract_speed * 60:.0f}")
                retracted = False
            out.append(f"G1 F{feed:.0f}")

            seg = np.diff(pts, axis=0)
            seg_len = np.linalg.norm(seg, axis=1)
            mid_th = 0.5 * (path.thickness[1:] + path.thickness[:-1])
            e = _extrusion_per_mm(printer, wall.line_width, mid_th) * seg_len
            for p, de, length, d in zip(pts[1:], e, seg_len, seg):
                if length < 1e-9:
                    continue
                out.append(f"G1 X{p[0]:.3f} Y{p[1]:.3f} Z{p[2]:.3f} E{de:.5f}")
                # Firmware slows the whole move if Z would exceed its max rate.
                z_rate = speed * abs(d[2]) / length
                max_z_rate = max(max_z_rate, z_rate)
                t = length / speed
                if z_rate > printer.max_z_speed:
                    t *= z_rate / printer.max_z_speed
                total_time += t
            total_e += float(e.sum())
            pos = pts[-1]

    out.append(END_GCODE.format(
        retract=printer.retract_length,
        retract_f=printer.retract_speed * 60,
        park_y=min(200.0, cy * 2 - 10),
        travel_f=travel_f,
    ))

    summary = {
        "layers": stats.layers,
        "min_thickness": stats.min_thickness,
        "max_thickness": stats.max_thickness,
        "max_slope_deg": stats.max_slope_deg,
        "filament_mm": total_e,
        "filament_g": total_e * math.pi * (printer.filament_diameter / 2) ** 2 * 1.24e-3,
        "time_min": total_time / 60.0,
        "max_z_rate": max_z_rate,
    }
    return "\n".join(out) + "\n", summary


def write_gcode(path: str, wall: WallParams, printer: PrinterParams) -> dict:
    text, summary = build_gcode(wall, printer)
    with open(path, "w") as fh:
        fh.write(text)
    return summary
